version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
      day: "monday"
      time: "06:00" # 9 am in romania
    commit-message:
      prefix: "build(deps)"
    reviewers:
      - "adrianbrad"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: "monday"
      time: "06:00" # 9 am in romania
    commit-message:
      prefix: "build(deps)"
    reviewers:
      - "adrianbrad"

  - package-ecosystem: docker
    directory: "/d8t"
    schedule:
      interval: weekly
      day: "monday"
      time: "06:00" # 9 am in romania
    commit-message:
      prefix: "build(deps)"
    reviewers:
      - "adrianbrad"