version: "2"
run:
  modules-download-mode: mod
linters:
  default: none
  enable:
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - decorder
    - dupl
    - dupword
    - err113
    - errcheck
    - errchkjson
    - errname
    - exhaustive
    - exptostd
    - fatcontext
    - forcetypeassert
    - gochecksumtype
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gosec
    - gosmopolitan
    - govet
    - grouper
    - iface
    - importas
    - inamedparam
    - ineffassign
    - interfacebloat
    - loggercheck
    - mirror
    - mnd
    - musttag
    - nilnesserr
    - nilnil
    - perfsprint
    - prealloc
    - reassign
    - recvcheck
    - revive
    - staticcheck
    - tagalign
    - tagliatelle
    - testableexamples
    - thelper
    - unused
    - usestdlibvars
    - usetesting
    - varnamelen
    - wsl
  settings:
    dupl:
      threshold: 300
    errcheck:
      exclude-functions:
        - (*net/http.Response.Body).Close
        - (io.ReadCloser).Close
        - (*database/sql.DB).Close
    gocognit:
      min-complexity: 20
    goconst:
      min-len: 2
      min-occurrences: 2
    gocritic:
      disabled-checks:
        - dupImport
        - whyNoLint
        - hugeParam
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    gocyclo:
      min-complexity: 20
    gosec:
      excludes:
        - G307
    misspell:
      locale: US
    nolintlint:
      require-explanation: true
      require-specific: false
      allow-unused: false
    revive:
      confidence: 0.1
      enable-all-rules: true
      rules:
        - name: nested-structs
          disabled: true
        - name: function-result-limit
          arguments:
            - 3
        - name: function-length
          disabled: true
        - name: banned-characters
          disabled: true
        - name: max-public-structs
          disabled: true
        - name: line-length-limit
          arguments:
            - 100
        - name: argument-limit
          disabled: true
        - name: cyclomatic
          disabled: true
        - name: file-header
          disabled: true
        - name: cognitive-complexity
          disabled: true
        - name: package-comments
          disabled: true
        - name: add-constant
          disabled: true
        - name: unhandled-error
          disabled: true
        - name: confusing-naming
          disabled: true
        - name: modifies-parameter
          disabled: true
        - name: var-naming
          arguments:
            - []
            - - WS
              - VM
    staticcheck:
      checks:
        - all
    tagliatelle:
      case:
        rules:
          json: snake
        use-field-name: true
    varnamelen:
      max-distance: 15
      ignore-names:
        - tx
        - err
        - pk
        - to
        - db
        - wg
        - id
        - DB
      ignore-type-assert-ok: true
      ignore-map-index-ok: true
      ignore-chan-recv-ok: true
      ignore-decls:
        - t testing.T
        - i int
        - T any
        - i *is.I
        - eg *errgroup.Group
        - ok bool
  exclusions:
    generated: lax
    rules:
      - linters:
          - err113
          - errcheck
          - forcetypeassert
          - gocognit
          - gocyclo
          - gosec
          - nilnil
          - varnamelen
        path: _test\.go
      - linters:
          - dupl
          - errcheck
          - forcetypeassert
          - gocyclo
          - gosec
          - revive
        path: mock
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofumpt
  settings:
    gofumpt:
      extra-rules: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
