repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.1.0
    hooks:
      - id: commitizen
  - repo: https://github.com/golangci/golangci-lint
    rev: v1.63.3
    hooks:
      - id: golangci-lint
        name: golangci-lint
        description: Fast linters runner for Go.
        entry: golangci-lint run --fix --config .golangci.yml
        types: [go]
        language: golang
        pass_filenames: false