name: grype

on:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  scan-source:
    name: scan-source
    runs-on: ubuntu-latest

    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: anchore/scan-action@27805bf3b4e84b4a5c980df22ed233c00390a439 # v7.4.2
        with:
          path: "."
          fail-build: true
